blank_issues_enabled: true
contact_links:
  - name: 💬 Discord
    url: https://unyt.org/discord
    about: Get help from the unyt.org community on Discord.
  - name: 📖 Documentation
    url: https://docs.unyt.org/manual/uix/getting-started
    about: Read the UIX documentation.
