blank_issues_enabled: true
contact_links:
  - name: 🔓 Vulnerability Reporting
    url: https://github.com/unyt-org/uix/security
    about: Report a security vulnerability for UIX.
  - name: 💬 Discord
    url: https://unyt.org/discord
    about: Get help from the unyt.org community on Discord.
  - name: 📖 Documentation
    url: https://docs.unyt.org/manual/uix/getting-started
    about: Read the UIX documentation.