on:
  release:
    types: [published]

env:
  CDN_TOKEN: ${{secrets.CDN_TOKEN}}

jobs:

  trigger-cdn-update:
    runs-on: ubuntu-latest

    steps:

      - name: Edit Release  
        uses: irongut/EditRelease@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          id: ${{ github.event.release.id }}
          body: $GITHUB_SHA


      - name: Make CDN Update Request
        run: |
          curl "https://cdn.unyt.org/update/$GITHUB_REPOSITORY?token=$CDN_TOKEN"
